defaultContentLanguage = "en"
googleAnalytics = ""
title = "Maistra"
disableFastRender = true

[taxonomies]
category = "categories"
tag = "tags"
property = "properties"
inspiration = "inspiration"
accesscodes = "accesscodes"
locations = "locations"

[outputs]
taxonomy = ["JSON", "HTML"]
term = ["JSON", "HTML"]
section = ["JSON", "HTML"]

[security]
[security.funcs]
getenv = ['^HUGO_', 'URL', 'TENANT_NAME', 'SENTRY_DSN', 'CONTEXT', 'TRUST_YOU_API_KEY', 'WWW_HOME_URL', 'GTM_ID']
